name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: /github/home/.buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: buildozer-${{ runner.os }}-

      - name: Clean previous builds
        run: buildozer android clean

      - name: Build Debug APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCalculator-APK
          path: bin/*.apk
